- name: variables for prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your name?
    private: true
  tasks:
  - name: print credintials
    ansible.builtin.debug:
      msg: "Hellow, username is : {{ username }}"